repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: stable
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
